### ISSUE TITLE
Customer Name is "?  ?" in 11 of our orders.  Please research and fix

### ISSUE THREAD

**Issue by jamiebianchini** [ludela/ludela.com#100]
I see that 11 orders have ?? listed as card name and customer name.  i have a feeling it's because they have "accounts" with us but we did not capture their name during the purchase process?  Nots sure what's up.  please see stripe and fix thanks!

![image](https://cloud.githubusercontent.com/assets/20848499/19237452/c9f9ed26-8eb1-11e6-8277-b7b32b6dd9cb.png)

**Comment by tmesser** [comment]
This one ends up looking like more of an issue than it is because this is partially what happens when a user abandons a cart - we might not have their name in the first place but we create a user for them so we can appropriately track the data and remarket to them via email.  Still, I will need to investigate this one more fully with a test order.

**Comment by tmesser** [comment]
Upon research, this is indeed what happens if a user begins a checkout process but does not fully complete it.  We properly grab names on fully completed orders.

As such, this is as-designed.

**Comment by jamiebianchini** [comment]
How can i see the names so we can reach out to our customers by name?  where is this data stored and how can we access it besides Stripe?  Can we see name, shipping address and the field in the past that was to be checked if they wanted a subscription?   we need to get some data on that field check box too.  thanks!

**Comment by tmesser** [comment]
There are a couple of situations this can occur:

1. The user abandons a cart without giving us their name
2. The user signed up for the newsletter, and never gave us their name.
3. The user signed up for the referral program, and never signed in and filled out their name.

In all of these situations, we never had the name to pass on.  The only customers in Stripe are the ones who have completed an order, or tried to check out and failed (which could be due to an invalid credit card number, a decline, etc).

We have all of this data (all the orders, signups to newsletter/referral program, etc) stored in our platform.  We're able to export this into CSV for you if that helps.

The subscriptions are a separate subject, and one that bears talking about a bit more. I think it's important to understand how this currently works on our software platform, and how it will need to change to do what you need.  Your specific needs with these bundles aren't handled by any current platform on the market and we will need to build a lot of this stuff out specially for you.

Right now:
1. Original pre-orders include scent as metadata on each order
2. New orders with current checkout flow:
    - Include individual scents as either subscription or singles purchases
    - Include selected scent as metadata on order when tied to a starter kit

We need to:
1. Update our API to support the dynamic product bundles that your checkout flow requires
2. Once that is implemented, we will migrate data such that each order will clearly distinguish subscriptions from individual scents and we will link bundled line items together based on add to cart from a bundle item. This will allow you to see in our dashboard (and/or export data) with each purchase item clearly differentiated  
3. Once you are shipping, we will convert the SKUs for subscription plans into separate plan objects for each subscriber and will handle the recurring billing and invoicing based on the customers specific plan configuration.
4. We are able to export all of this data as needed and create a report for you -- after our API is updated you'll be able to access all of this in our dashboard and export data from our end yourself

**Comment by davidtai** [comment]
Upon investigation: We had a bug in the ui that was causing this, there was no data loss, we are running a migration to fix this.
